# LambdaTest AI Cloud Configuration
project_id: "01JRWGPT1RTKGTPDYHVJWJ7X01"
folder_id: "01JX0BMZ6JG4FVDEQQQZ2G04R5"
#assignee: your_user_id
#environment_id: environment_id
test_url: "https://demo.lambdatestinternal.com"